### ISSUE TITLE
Please specify a license 

### ISSUE THREAD

**Issue by beeman** [faceleg/loopback-datasource-juggler-paginate#2]
Hi @faceleg, I'm thinking about creating a mixin for loopback that adds pagination and it would be great if you could add a license that allows me to use parts of your code. Personally I like the MIT license. 

Thanks for considering!

**Comment by faceleg** [comment]
Me too! Done!

**Comment by faceleg** [comment]
:dancer:

**Comment by beeman** [comment]
Awesome @faceleg, thanks a lot!
